name: Build and deploy .NET Core application to Web App PrintMeAPI
on:
  push:
    branches:
    - release
env:
  AZURE_WEBAPP_NAME: PrintMeAPI
  AZURE_WEBAPP_PACKAGE_PATH: PrintMe.API/publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: PrintMe.API
permissions:
  id-token: write  # Grant write permissions for id-token
  contents: read   # Grant read permissions for contents
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CA91DA42ACF24FDEB6A709A1D2423E74 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_11E59C390119493FA65707B9A09FC20B }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_910F90A460FD4DA6852637E44C0A4CD8 }}
        allow-no-subscriptions: true
        enable-AzPSSession: true
 
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.PrintMeAPI_A498 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
